config/routes.rb
Rails.application.routes.draw do
  
  get '/cart' => 'cart#index'
  get '/cart/clear' => 'cart#clearCart'
  get '/cart/:id' => 'cart#add'
  get '/products' => 'products#index'
  get '/services' => 'services#index'
  
  devise_for :users
  

  root 'welcome#index'
  

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  #force user to login 
  #before_action :authenticate_user!
end

app/controllers/cart_controller.rb
class CartController < ApplicationController

before_action :authenticate_user!
  
  def add
    id = params[:id]
    if session[:cart] then
      cart = session[:cart]
    else
      session[:cart]={}
      cart = session[:cart]
    end  
    
    if cart[id] then
      cart[id] = cart[id] + 1
    else
      cart[id] = 1
    end
    redirect_to :action => :index  
  end
  
  def clearCart
    session[:cart]=nil
    redirect_to :action => :index
  end  
  
  def index
    if session[:cart] then
      @cart = session[:cart]
    else
      @cart = {}
    end
  end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  def index
   
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/cart/index.html.erb
<h1>Your Cart</h1>
<% if @cart.empty? %>
    <p>Your cart is currently empty.</p>
<% else %>    
<%= link_to 'Empty your cart', cart_clear_path %>
<% end %>
<br><br><br>

<% total = 0 %>
<ol>
<% @cart.each do |id,quantity| %>
    <% service = Service.find_by_id(id) %>
    <!--<%# product = Product.find_by_id(id) %>
    
    <li>
        <%#= product.title %>
        <p><%#= product.description %></p>
        <p><%#= number_to_currency(product.price,unit: "Rs ") %></p>
        <p>Quantity : <%#= quantity %></p>
        
    </li>
    <%# total += quantity * product.price %>
    -->
    <li>
        <%= service.title %>
        <p><%#= product.description %></p>
        <p><%= number_to_currency(service.price,unit: "Rs ") %></p>
        <p>Quantity : <%= quantity %></p>
        
    </li>
    
    <% total += quantity * service.price %>
    
<% end %>    

<p><b><%= number_to_currency(total,unit: "Rs ") %></b></p>
</ol>
<% if total > 0 %>
<button type="button" class="btn btn-success" style="float:right;width:100px;">Pay</button>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer-distributed" style="padding:50px;">

			<div class="footer-left">

				 <img src="/assets/logo1.png" width="100%">

				<p class="footer-links">
					<a href="#">Home</a>
					·
					<a href="#">About</a>
					.
					<a href="#">Contact</a>
				</p>

				<p class="footer-company-name">FarmTrade &copy; 2016</p>
			</div>

			<div class="footer-center">

				<div>
					<i class="fa fa-map-marker"></i>
					<p><span>30/3, Dr. Rajkumar Road</span> Bangalore, India</p>
				</div>

				<div>
					<i class="fa fa-phone"></i>
					<p>+91 22325626</p>
				</div>

				<div>
					<i class="fa fa-envelope"></i>
					<p><a href="mailto:support@farmtrade.com">support@farmtrade.com</a></p>
				</div>

			</div>

			<div class="footer-right">

				<p class="footer-company-about">
					<span>About the company</span>
At FarmTrade, our vision is to be India's most customer centric company ,to build a place where people can come to find anything and everything related to farming, be it products or services. We aim to give our customers more of what they want – vast selection, low prices, fast and reliable delivery, and a trusted and convenient online shopping experience – and provide sellers a world-class e-commerce platform.</p>

				<div class="footer-icons">

					<a href="#"><i class="fa fa-facebook"></i></a>
					<a href="#"><i class="fa fa-twitter"></i></a>
					<a href="#"><i class="fa fa-linkedin"></i></a>
					

				</div>

			</div>

		</footer>

app/views/layouts/_header.html.erb
<div class="navbar navbar-default navbar-fixed-top" id="header">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        
        
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <div class="row" style="text-align:center;">
            <ul class="nav navbar-nav navbar-right">
              <li>
              <% if !user_signed_in? %>
                <%= link_to new_user_registration_path do %>
                  <span class="glyphicon glyphicon-user"></span>
                  Sign up
                 <% end %>
              <% end %>
              </li>
              <li>
              <% if !user_signed_in? %>
                <%= link_to new_user_session_path do %>
                  <span class="glyphicon glyphicon-log-in"></span>
                  Sign in
                 <% end %>
              <% end %>
              </li>
              <li class="usr_email">
              <% if user_signed_in? %>
              <%= "Hi, " %>
              <%= current_user.email.split('@')[0] %>
              <% end %>  
              </li>
              <li>
              <% if user_signed_in? %>
              <%= link_to destroy_user_session_path,method: :delete do %>
                <span class="glyphicon glyphicon-log-out"></span>
                Sign out
                <% end %>
              <% end %>
              </li>
  					</ul>
          </div>
          <div class="row" style="text-align:center;">
            <div class="col-md-12">
              <div class="col-md-3">
                <%= link_to image_tag("logo1.png",height:70),root_path %>
              </div>
              <div class="col-md-7">
                   <form class="navbar-form" role="search">
                                    <div class="input-group add-on" style="padding-top: 8px">
                                        <input class="form-control" placeholder="Search" name="srch-term" id="srch-term" type="text" size="85">
                                         <div class="input-group-btn">
                                            <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i>
                                           </button>
                                          </div>
                                        </div>
                         </form>
              </div>
              <div class="col-md-2" style="padding-top:14px;">
                 <%= link_to cart_path,class:"btn btn-default",style:"color:black;" do %>
                   <span class="glyphicon glyphicon-shopping-cart"></span>
                   cart
                  <% end %>
              </div>
            </div>
          </div>
          <div class="row" style="text-align:center;">
            <div class="nav navbar-nav" style="float:inherit;">
              <%= link_to "Products", products_path %> <span style="color:white;">|</span> 
              <%= link_to "Services", services_path %>
            </div>
          </div>
          
          
          
          
          
					
        </div>
      </div>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "FarmTrade" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>
    
	
	
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">

	<link href="https://fonts.googleapis.com/css?family=Cookie" rel="stylesheet" type="text/css">

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>


    <%= render "layouts/header" %>
<div class="row">
<div class="container">
          <%= bootstrap_flash %>
          <%= yield %>
</div>
</div>
          
  <%= render "layouts/footer" %> 

  </body>
</html>

app/views/pages/products.html.erb
<center>
 <div class="col-md-12">
    <div class="row">
      <div class="col-md-6">
        <a href="#"><img src="assets/seed3.jpg" class="img-thumbnail" width=50%></a>
        <h4>Seeds</h4>
      </div>
      <div class="col-md-6">
        <a href="#"><img src="assets/fertiliser1.jpg" class="img-thumbnail" width=50%></a>
        <h4>Fertilisers</h4>
      </div>
      </div>
      
      <div class="row">
      <div class="col-md-6">
       <a href="#"> <img src="assets/tool2.jpg" class="img-thumbnail" width=50%></a>
        <h4>Tools</h4>
      </div>
      <div class="col-md-6">
       <a href="#"> <img src="assets/produce1.jpg" class="img-thumbnail" width=50%></a>
        <h4>Produce</h4>
      </div>
      </div>
    </div>
</center>

app/views/pages/services.html.erb
<center>
 <div class="col-md-12">
    <div class="row">
      <div class="col-md-3">
        <img src="assets/sowing.jpg" class="img-thumbnail" width="70%">
        <h4>Sowing</h4>
      </div>
      <div class="col-md-3">
        <img src="assets/ploughing.jpg" class="img-thumbnail" width="70%">
        <h4>Ploughing</h4>
      </div>
      
      <div class="col-md-3">
        <img src="assets/irrigation.jpg" class="img-thumbnail" width="70%">
        <h4>Irrigation</h4>
      </div>
       <div class="col-md-3">
        <img src="assets/bullockcarts.jpg" class="img-thumbnail" width="70%">
        <h4>Rent bullockcarts</h4>
      </div>
      </div>
      
      <div class="row">
      <div class="col-md-3">
        <br><img src="assets/harvesting.jpg" class="img-thumbnail" width="70%">
        <h4>Harvesting</h4>
      </div>
      <div class="col-md-3">
       <br> <img src="assets/animalinsurance.jpg" class="img-thumbnail" width="70%">
        <h4>Animal Insurance</h4>
      </div>
      <div class="col-md-3">
        <br><br><img src="assets/crop insurance.jpg" class="img-thumbnail" width="80%" >
        <h4>Crop insurance</h4>
      </div>
      </div>
    </div>
    </center>

app/views/products/index.html.erb
<center> 
 <div class="row">
   <div class="col-md-12">  <br> 
         
   <div class="col-md-6"> 
           <a href="seeds.html"><img src="/assets/seed3.jpg" class="img-thumbnail" width="35%"></a>       
             <h4>Seeds</h4>
    </div>      
     <div class="col-md-6">       
       <a href="fertiliserfinal.html"><img src="/assets/fertiliser1.jpg" class="img-thumbnail" width=33%></a>
        <h4>Fertilisers</h4>     
      </div>   
      </div>
      
      <br>

      <div class="row">
      <div class="col-md-6">
       <a href="toolfinal.html"> <img src="/assets/tool2.jpg" class="img-thumbnail" width=33%></a>
        <h4>Tools</h4>
      </div>
      <div class="col-md-6">
       <a href="produce.html"> <img src="/assets/produce1.jpg" class="img-thumbnail" width=37%></a>
        <h4>Produce</h4>
      </div>
      </div>
    
    </div><br>
    </center>

app/views/services/_cropinsurance.html.erb
<div class="row">
 <div class="container-fluid">
   <div class="col-md-12">

               <center><h1> <strong>Pradhan Mantri Fasal Bima Yojana</strong> </h1>
              <img src="/assets/crop insurance.jpg" style="width: 50%">
              </center>
              <br>
          
         
             
                    <div class="container" style="padding-top:15px;padding-bottom:15px;padding-left: 30px;padding-right:30px; margin-top:25px;margin-bottom: 30px; ">
                    
                    <p>In the <strong>Pradhan Mantri Fasal Bima Yojana (Prime Minister Crop Insurance Scheme)</strong> launched by <strong>Honourable Prime Minister Shri Narendra Modi </strong>on 13th January 2016 the premium rates to be paid by the farmers have been brought down substantially 
                    so as to enable more farmers avail insurance cover against crop loss on account of natural calamities. <br><br>
<strong>Under the new scheme,</strong> farmers will have to pay a uniform premium of two per cent for all kharif crops and 1.5 per cent for all rabi crops. For annual commercial and horticultural crops, farmers will have to pay a premium of 5 per cent. The remaining share of the premium, as in previous schemes, will continue to be borne equally by the Centre and the respective state governments.<br><br>
                  <strong>To apply for insurance under Pradhan Mantri Fasal Bima Yojana , Click on Apply :
                  <a href="http://agri-insurance.gov.in/Login.aspx" style="color: black"><h3><center> Apply </center></h3></a></strong>
                  </p>
  
                    </div>  
            
        </div>
    </div>
</div>

app/views/services/index.html.erb
<center>
 <div class="row">
    <br><br>
     <div class="col-md-12">
            <div class="col-md-3">
              <a href="sowing.html"><img src="/assets/sowing.jpg" class="img-thumbnail" width="70%"></a>
              <h4>Sowing</h4>
            </div>
            <div class="col-md-3">
              <a href="ploughing.html"><img src="/assets/ploughing.jpg" class="img-thumbnail" width="70%"></a>
              <h4>Ploughing</h4>
            </div>
      
            <div class="col-md-3">
             <a href="irrigation.html"> <img src="/assets/irrigation.jpg" class="img-thumbnail" width="70%"></a>
              <h4>Irrigation</h4>
            </div>
             <div class="col-md-3">
              <a href="bullockcarts.html"><img src="/assets/bullockcarts.jpg" class="img-thumbnail" width="70%"></a>
              <h4>Rent bullockcarts</h4>
            </div>
          </div>
  </div>
      <br>
      <div class="row">
          <div class="col-md-12">
              <div class="col-md-3">
                <a href="harvesting.html"><img src="/assets/harvesting.jpg" class="img-thumbnail" width="70%"></a>
                <h4>Harvesting</h4>
              </div>
              <div class="col-md-3">
                <img src="/assets/animalinsurance.jpg" class="img-thumbnail" width="70%">
                <h4>Animal Insurance</h4>
              </div>
              <div class="col-md-3">
                <a href="cropinsurance.html"><img src="/assets/crop insurance.jpg" class="img-thumbnail" width="80%" ></a>
                <h4>Crop insurance</h4>
              </div>
      </div>
      </div>

</center>

app/views/welcome/index.html.erb
   
	<center>	
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    
    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
      <div class="item active">
        <img src="/assets/b1.jpg"  width="860" height="345">
      </div>

      <div class="item">
        <img src="/assets/b2.jpg"  width="860" height="345">
      </div>
    
      
      <div class="item">
        <img src="/assets/b4.jpg" width="860" height="345">
      </div>
    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
  </center>
		